# Generated by Django 6.0 on 2026-01-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lei', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('exchange', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('FYE_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('special_sits', models.TextField(blank=True, default='')),
                ('history', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=50)),
                ('filing_date', models.DateField()),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'filing_date'], name='companies_f_company_421ec8_idx'), models.Index(fields=['company', 'filing_date', 'filing_type'], name='companies_f_company_dcb1f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end_date', models.DateField()),
                ('statement', models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow')], max_length=2)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'period_end_date'], name='companies_f_company_f1bed7_idx'), models.Index(fields=['company', 'statement', 'metric'], name='companies_f_company_5a4349_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'period_end_date', 'statement', 'metric'), name='uniq_company_period_statement_metric')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'followed_at'], name='companies_f_user_id_d8eace_idx'), models.Index(fields=['company', 'followed_at'], name='companies_f_company_2f26b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uniq_user_company_follow')],
            },
        ),
    ]
