# Generated by Django 6.0 on 2026-01-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_lei_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('ticker', 'exchange'), name='uniq_ticker_exchange'),
        ),
    ]
