# Generated by Django 6.0 on 2026-01-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='companies_n_user_id_0e7cab_idx',
            old_name='companies_n_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='stockprice',
            new_name='companies_s_company_9a49ed_idx',
            old_name='companies_s_company_5e8c5e_idx',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
