# Generated by Django 6.0 on 2026-01-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
