# Generated by Django 6.0 on 2025-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_remove_emailverificationtoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="folder",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
