# Generated by Django 6.0 on 2026-01-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_discussion_threads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discussionmessage',
            new_name='companies_d_thread__c86275_idx',
            old_name='companies_d_thread__38fbf3_idx',
        ),
        migrations.RenameIndex(
            model_name='discussionmessage',
            new_name='companies_d_created_66da5f_idx',
            old_name='companies_d_created_0668f8_idx',
        ),
        migrations.RenameIndex(
            model_name='discussionthread',
            new_name='companies_d_company_efa293_idx',
            old_name='companies_d_company_7995d5_idx',
        ),
    ]
