# Generated by Django 6.0 on 2025-01-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_chat_sessions"),
        ("companies", "0011_rename_companies_d_thread__38fbf3_idx_companies_d_thread__c86275_idx_and_more"),
    ]

    operations = []
