# Generated by Django 6.0 on 2025-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_merge_0011_chat_sessions_and_rename"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="noted_by", to="companies.company")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="note_companies", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="notecompany",
            constraint=models.UniqueConstraint(fields=("user", "company"), name="uniq_user_company_note"),
        ),
        migrations.AddIndex(
            model_name="notecompany",
            index=models.Index(fields=["user", "created_at"], name="companies_n_user_id_b6a7aa_idx"),
        ),
    ]
