# Generated by Django 6.0 on 2026-01-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_merge_0011_chat_sessions_and_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='companies_c_session_506589_idx',
            old_name='companies_c_session_51dd6d_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='companies_c_company_42c3e9_idx',
            old_name='companies_c_company_1a97f0_idx',
        ),
    ]
