# Generated by Django 6.0 on 2025-01-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_note_company"),
        ("companies", "0013_rename_companies_c_session_51dd6d_idx_companies_c_session_506589_idx_and_more"),
    ]

    operations = []
