# Generated by Django 6.0.1 on 2026-02-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_merge_0013_note_company_and_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('basic_filters', models.JSONField(default=dict)),
                ('nl_query', models.TextField(blank=True, default='')),
                ('generated_sql', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notecompany',
            new_name='companies_n_user_id_624076_idx',
            old_name='companies_n_user_id_b6a7aa_idx',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedscreen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_screens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedscreen',
            index=models.Index(fields=['user', '-updated_at'], name='companies_s_user_id_73d4b0_idx'),
        ),
    ]
