# Generated by Django 6.0.1 on 2026-02-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alertpreference_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financial',
            name='companies_f_company_f1bed7_idx',
        ),
        migrations.RemoveIndex(
            model_name='financial',
            name='companies_f_company_5a4349_idx',
        ),
    ]
