# Generated by Django 6.0.1 on 2026-02-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_drop_redundant_financial_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.company'),
        ),
    ]
