# Generated by Django 6.0.1 on 2026-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_drop_financial_fk_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='metric',
            field=models.CharField(max_length=255),
        ),
    ]
