# Generated by Django 6.0.1 on 2026-02-24 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_metric_fk_drop_currency'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprice',
            name='companies_s_company_9a49ed_idx',
        ),
        migrations.AlterField(
            model_name='financial',
            name='metric',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.financialmetric'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
